using System.Reflection;
using System.Runtime.InteropServices;

[assembly: Guid("D83EE60E-7628-4E43-B7A2-B94D7F2B9F9A")]
[assembly: AssemblyTitle("NightSage")]
[assembly: AssemblyDescription("AI target discovery and imaging planner for N.I.N.A.")]
[assembly: AssemblyCompany("grm")]
[assembly: AssemblyProduct("NightSage")]
[assembly: AssemblyCopyright("Copyright © 2026")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("0.2.0.0")]
[assembly: AssemblyFileVersion("0.2.0.0")]
[assembly: AssemblyInformationalVersion("0.2.0-beta.1")]
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.2.0.9001")]
[assembly: AssemblyMetadata("ShortDescription", "AI target discovery, native framing, mosaics and acquisition planning for N.I.N.A.")]
[assembly: AssemblyMetadata("License", "MPL-2.0")]
[assembly: AssemblyMetadata("LicenseURL", "https://www.mozilla.org/en-US/MPL/2.0/")]
[assembly: AssemblyMetadata("Repository", "https://github.com/grm/nina.plugin.nightsage")]
[assembly: AssemblyMetadata("Homepage", "https://github.com/grm/nina.plugin.nightsage")]
[assembly: AssemblyMetadata("ChangelogURL", "https://github.com/grm/nina.plugin.nightsage/blob/main/CHANGELOG.md")]
[assembly: AssemblyMetadata("Tags", "AI,Planning,Framing,Mosaic,Target Scheduler,Automation")]
[assembly: AssemblyMetadata("LongDescription", @"NightSage discovers targets for the active N.I.N.A. setup, builds validated acquisition plans, embeds the native N.I.N.A. Framing Assistant for composition and mosaics, and creates Target Scheduler projects while reusing existing exposure templates as the technical source of truth.")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("windows")]
[assembly: ComVisible(false)]
