using System.Reflection;
using System.Runtime.InteropServices;

[assembly: Guid("D83EE60E-7628-4E43-B7A2-B94D7F2B9F9A")]
[assembly: AssemblyTitle("NightSage")]
[assembly: AssemblyDescription("AI target discovery and imaging planner for N.I.N.A.")]
[assembly: AssemblyCompany("grm")]
[assembly: AssemblyProduct("NightSage")]
[assembly: AssemblyCopyright("Copyright © 2026")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("0.1.2.2")]
[assembly: AssemblyFileVersion("0.1.2.2")]
[assembly: AssemblyInformationalVersion("0.1.2-alpha.3")]
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.2.0.9001")]
[assembly: AssemblyMetadata("License", "MPL-2.0")]
[assembly: AssemblyMetadata("LicenseURL", "https://www.mozilla.org/en-US/MPL/2.0/")]
[assembly: AssemblyMetadata("Repository", "https://github.com/grm/nina.plugin.nightsage")]
[assembly: AssemblyMetadata("Homepage", "https://github.com/grm/nina.plugin.nightsage")]
[assembly: AssemblyMetadata("Tags", "AI,Planning,Target Scheduler,Automation")]
[assembly: AssemblyMetadata("LongDescription", @"NightSage turns the active N.I.N.A. profile into an AI-assisted astrophotography planning workspace. The planner lives on the plugin page, embeds the native N.I.N.A. Framing Assistant, creates framing-aware mosaics in Target Scheduler, and uses existing exposure templates as the technical source of truth.")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("windows")]
[assembly: ComVisible(false)]
